---
title: "Conferência de inventários florestais em campo"
subtitle:
titlerunning: Conferência 10%
date: "`r format(Sys.time(), '%d %b %Y %H:%M:%S %Z')`"
author: "Eric B. Gorgens, UFVJM"
output:
  bookdown::word_document2: default
  pdf_document: default
  bookdown::html_document2: default
  bookdown::pdf_book:
    base_format: rticles::springer_article
    extra_dependencies: booktabs
abstract: "[pt] Abstract..."
bibliography: bibliografia.bib
biblio-style: spbasic
authors:
- name: Eric Bastos Gorgens
  address: Universidade Federal dos Vales do Jequitinhonha e Mucuri, Campus JK, Diamantina, MG, Brasil. CEP 39100-000
  email: eric.gorgens@ufvjm.edu.br
csl: abnt.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE,
                      message = FALSE,
                      echo = FALSE)
```

```{r load-libraries, include=FALSE}
# load libraries
library(tidyverse)
library(ggbeeswarm)
library(bookdown)
```

# Introdução {#intro}

```{r get-intro, child="01introducao.Rmd"}
```


# Material e métodos {#material}

```{r get-mm, child="02material.Rmd"}
```

# Resultados {#resultados}

```{r get-mm, child="03resultados.Rmd"}
```

# Discussão {#discussao}

```{r get-mm, child="04discussao.Rmd"}
```

# Conclusão {#conclusao}

```{r get-mm, child="05conclusao.Rmd"}
```

# Referências